# Site settings
baseurl = "https://ieee-satml.github.io/"
languageCode = "en-us"
title = "IEEE SaTML 2023"
theme = "syna"
enableGitInfo = true
version = "0.17.3"

# Google Analytics tracking
googleAnalytics = ""

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "IEEE SaTML 2023"
  description = "IEEE Conference on Secure and Trustworthy Machine Learning"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.iso"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = ""

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#343538"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/participate"
  name = "Participate"
  weight = 20
  identifier = "participate"

[[menu.main]]
  url = "/participate"
  name = "Participate"
  weight = 10
  parent = "participate"

[[menu.main]]
  url = "/participate-cfp"
  name = "Call For Papers"
  weight = 20
  parent = "participate"

[[menu.main]]
  url = "/participate-cfc"
  name = "Call For Competitions"
  weight = 30
  parent = "participate"

[[menu.main]]
  url = "/attend"
  name = "Attend"
  weight = 30

[[menu.main]]
  url = "/people"
  name = "People"
  weight = 40

[[menu.footer]]
  url = "#"
  name = "Link"
  weight = 10

[[menu.footer]]
  url = "#"
  name = "Long Link"
  weight = 30

[[menu.footer]]
  url = "#"
  name = "Tiny Link"
  weight = 30

[[menu.copyright_footer]]
  url = "#"
  name = ""
  weight = 10


[[menu.footer_social]]
  weight = 20
  name = "twitter"
  pre = "fab fa-twitter"
  url = "https://twitter.com/satml_conf"
